stages:
  - test
  - build

run_tests:
  stage: test
  image: python:3
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=src pytest -v --junitxml=report.xml --cov=src --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: ${CI_PROJECT_DIR}/report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build_pip:
  stage: build
  image: python:3
  script:
    - make venv
    - make install
  artifacts:
    name: "${CI_PROJECT_TITLE}-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/*
    expire_in: 1 days
