#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2023 KUNBUS GmbH
#
# This script updates the node-red-contrib-revpi-nodes, which must always be
# installed for the appropriate server version.
#
# As long as node-red is installed in /home/pi/.node-red, we have to
# upgrade the nodes in that location as user pi.

NODE_RED_ROOT="/home/pi/.node-red"
REVPI_NODES_VERSION="1.1.0"

# Check node red installation directory
if [ ! -d "${NODE_RED_ROOT}" ]; then
    echo "NodeRED is not installed at '${NODE_RED_ROOT}'" >&2
    exit 1
fi

# Check user is root or pi, both can upgrade the nodes
if [ "$(id -un)" == "pi" ]; then
    # This will install/upgrade the revpi nodes of this package as pi user
    /usr/bin/npm install \
        --save \
        --prefix "${NODE_RED_ROOT}" \
        "/usr/share/noderedrevpinodes-server/npm-install/${REVPI_NODES_VERSION}.tar.gz"

else
    echo "This script must be executed as user pi." >&2
    exit 1

fi
